# Generated by Django 3.2.4 on 2021-11-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=40)),
                ('student_address', models.TextField()),
                ('student_marks', models.FloatField()),
            ],
        ),
    ]
